# Numpy

In [3]:
#Import Numpy Library

import numpy as np

In [4]:
#create simple array from the list

arr = np.array([[1,2,33,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.ndim

2

In [7]:
#shape of the array

arr.shape

(2, 4)

In [8]:
arr = np.array([1,2,3,4])

In [9]:
arr

array([1, 2, 3, 4])

In [10]:
arr.ndim

1

In [13]:
arr3 = np.array([[1,2,33,4,58],[5,6,7,8,89],[89,16,17,88,25]])

In [16]:
arr3.shape

(3, 5)

In [15]:
arr3

array([[ 1,  2, 33,  4, 58],
       [ 5,  6,  7,  8, 89],
       [89, 16, 17, 88, 25]])

In [20]:
arr.data


# Random Number Generator using numpy

In [21]:
from numpy import random

In [28]:
from numpy import random
x= random.randint(10)
print(x)

5


In [33]:
x= random.randint(1000)
y= random.randint(1000)
z= random.randint(1000)
w= random.randint(1000)
e= random.randint(1000)

In [34]:
print(x)
print(y)
print(z)
print(w)
print(e)

706
592
384
773
702


In [35]:
#Generate Random Float

x= random.rand()
print(x)

0.17653743485944062


In [38]:
for i in range(40):
    x= random.rand()
    print(x)


0.2566230038469848
0.6479977465292327
0.5030640593763117
0.8729679687145558
0.5551289860988066
0.361663497653408
0.7520154209853722
0.717715928907141
0.6932316262930102
0.617208629740413
0.5724015917785852
0.029281653228062754
0.7240195787443743
0.2976358125644134
0.10089944702255016
0.19884035068609307
0.013788777477672931
0.581498127808266
0.1699334057321773
0.9077137565027587
0.3830359724726946
0.37717758242799815
0.8243389197391374
0.8104688214772408
0.9233574927975129
0.7778434824616598
0.180934019753608
0.7770122050144058
0.5724820072764764
0.6320232365120437
0.3463043391373608
0.3558673685959066
0.3029696160958898
0.6891127075460423
0.8564227660894516
0.6880093498543365
0.10298392561880754
0.0506415650835037
0.15251371788720358
0.563444090590141


In [42]:
#Generate Random Array

from numpy import random
x= random.randint(100, size=(5))
print(x)

[49 16 73  4 42]


In [44]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

from numpy import random
x= random.randint(100, size=(3, 10))
print(x)


[[96 18 64 43 69 40 50 67 56 11]
 [15 90 92 53 15 73 61 67 88  9]
 [22  6  4 27 79 70  6 51 86 45]]


In [45]:
x.shape

(3, 10)

# Measure of Central Tendency

In [46]:
import numpy as np

arr = np.array([[1,23,78], [98,60,75],[79,25,48]])
print(arr)

#min function
print(np.amin(arr))
#max function
print(np.amax(arr))

[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [47]:
np.mean(arr)

54.111111111111114

In [48]:
np.median(arr)

60.0

In [49]:
np.std(arr)

30.296477405960523

In [50]:
np.var(arr)

917.8765432098766

# Array Broadcasting in Numpy

In [51]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [52]:
a+b

array([3., 4., 5.])

In [53]:
a*b

array([2., 4., 6.])